{
  "tests": [
    {
      "name": "calls a nonexistent method",
      "file": "test/resources/sample-tests/broken.test.js",
      "tests": [],
      "duration": 0,
      "skip": false,
      "todo": false,
      "error": {
        "failureType": "testCodeFailure",
        "cause": {},
        "code": "ERR_TEST_FAILURE"
      }
    },
    {
      "name": "module",
      "file": "test/resources/sample-tests/nested.test.js",
      "tests": [
        {
          "name": "function",
          "file": "test/resources/sample-tests/nested.test.js",
          "tests": [
            {
              "name": "behavior",
              "file": "test/resources/sample-tests/nested.test.js",
              "tests": [
                {
                  "name": "asserts 1 === 1",
                  "file": "test/resources/sample-tests/nested.test.js",
                  "tests": [],
                  "duration": 0,
                  "skip": false,
                  "todo": false
                },
                {
                  "name": "fails",
                  "file": "test/resources/sample-tests/nested.test.js",
                  "tests": [],
                  "duration": 0,
                  "skip": false,
                  "todo": false,
                  "failure": {
                    "failureType": "testCodeFailure",
                    "cause": {
                      "generatedMessage": false,
                      "code": "ERR_ASSERTION",
                      "actual": 1,
                      "expected": 2,
                      "operator": "strictEqual"
                    },
                    "code": "ERR_TEST_FAILURE"
                  }
                }
              ],
              "duration": 0,
              "skip": false,
              "todo": false,
              "error": {
                "failureType": "subtestsFailed",
                "cause": {},
                "code": "ERR_TEST_FAILURE"
              }
            }
          ],
          "duration": 0,
          "skip": false,
          "todo": false,
          "error": {
            "failureType": "subtestsFailed",
            "cause": {},
            "code": "ERR_TEST_FAILURE"
          }
        }
      ],
      "duration": 0,
      "skip": false,
      "todo": false,
      "error": {
        "failureType": "subtestsFailed",
        "cause": {},
        "code": "ERR_TEST_FAILURE"
      }
    },
    {
      "name": "behavior",
      "file": "test/resources/sample-tests/skip.test.js",
      "tests": [
        {
          "name": "skipped test",
          "file": "test/resources/sample-tests/skip.test.js",
          "tests": [],
          "duration": 0,
          "skip": true,
          "todo": false
        }
      ],
      "duration": 0,
      "skip": false,
      "todo": false
    },
    {
      "name": "callback timing out",
      "file": "test/resources/sample-tests/timeout.test.js",
      "tests": [],
      "duration": 0,
      "skip": false,
      "todo": false,
      "error": {
        "failureType": "testTimeoutFailure",
        "cause": {},
        "code": "ERR_TEST_FAILURE"
      }
    },
    {
      "name": "my pending test",
      "file": "test/resources/sample-tests/todo.test.js",
      "tests": [
        {
          "name": "eventually it will assert something",
          "file": "test/resources/sample-tests/todo.test.js",
          "tests": [],
          "duration": 0,
          "skip": false,
          "todo": false
        }
      ],
      "duration": 0,
      "skip": false,
      "todo": true
    }
  ],
  "duration": 0
}
